# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Run all lint checks
name: lint
on: [push, pull_request]

jobs:

  ################
  # Verible Lint #
  ################
  verilog:
    name: Verilog Sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chipsalliance/verible-linter-action@main
        with:
          paths: |
            ./src
            ./vendor/lowrisc_opentitan/src
          exclude_paths: 
          extra_args: "--rules=-interface-name-style --lint_fatal --parse_fatal --waiver_files lint/verible.waiver"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reviewdog_reporter: github-check


  #####################
  # Vendor Up-to-Date #
  #####################
  # Check that all vendored sources are up-to-date.
  check-vendor:
    name: Vendor Up-to-Date
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install bender
      run: curl --proto '=https' --tlsv1.2 https://pulp-platform.github.io/bender/init -sSf | sh -s -- 0.26.0
    - name: Re-vendor and diff
      run: ./bender import --refetch && git diff --exit-code
